name: Linux Build

on: push

jobs:
  build:
    name: Build on Ubuntu
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        ref: 7a878bf3587bcdaa358c43e5bccb372006011d25

    - name: Build C Code
      run: |
       cmake .
       make
